name: Analyze modified files

#on:
#  pull_request:
#    paths:
#      - "**.py"
#  push:
#    paths:
#      - "**.py"
on: [push]

env:
#  BASE: ${{ github.event.pull_request.base.sha || github.event.push.before }}
#  HEAD: ${{ github.event.pull_request.head.sha || github.event.push.after }}
  BASE: ${{ github.event_name }}
  HEAD: ${{ github.event }}
  HEAD22: ${{ github.event_type }}

jobs:
  flake8-or-mypy:
    strategy:
      fail-fast: false
      matrix:
        task: [flake8, mypy]

    name: ${{ matrix.task }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Determine modified files"
        run: |
          git fetch origin $BASE $HEAD
          DIFF=$(git diff --diff-filter=d --name-only $BASE...$HEAD -- "*.py")
          echo "modified files:"
          echo "$DIFF"
          echo "diff=${DIFF//$'\n'/$' '}" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        if: env.diff != ''
        with:
          python-version: 3.8

      - name: "Install dependencies"
        if: env.diff != ''
        run: |
          python -m pip install --upgrade pip ${{ matrix.task }}
          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes

      - name: "flake8: Lint modified files"
        continue-on-error: true
        if: env.diff != '' && matrix.task == 'flake8'
        run: |
          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}

      - name: "mypy: Type check modified files"
        continue-on-error: true
        if: env.diff != '' && matrix.task == 'mypy'
        run: |
          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
