name: Analyze modified files

on:
  pull_request:
    paths:
      - "**.py"

env:
  BASE_SHA: ${{ github.event.pull_request.base.sha }}
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  flake8-and-mypy:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flake8 mypy
          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes

      - name: Determine modified files
        run: |
          git fetch origin $BASE_SHA $HEAD_SHA
          DIFF=$(git diff --diff-filter=d --name-only $BASE_SHA...$HEAD_SHA -- "*.py")
          echo "modified files:"
          echo "$DIFF"

#          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
#          echo "diff<<$EOF
#          $DIFF
#          $EOF" >> $GITHUB_ENV
          echo "${DIFF//$'\n'/$' '}"

      - name: Lint modified files with flake8
#        if: env.diff != ""
        run: |
          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}

#      - name: Type check modified files with mypy
#        if: env.diff != "" && (success() || failure())
#        run: |
#          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
