name: Analyze modified files

#on:
#  pull_request:
#    paths:
#      - "**.py"
#  push:
#    paths:
#      - "**.py"
on: [push]

env:
#  BASE: ${{ github.event.pull_request.base.sha || github.event.push.before }}
#  HEAD: ${{ github.event.pull_request.head.sha || github.event.push.after }}
  HEAD1: ${{ github.event.push.after }}
  HEAD2: ${{ github.event.push.base_ref }}
  HEAD3: ${{ github.event.push.before }}
  HEAD4: ${{ github.event.push.compare }}
  HEAD5: ${{ github.event.push.created }}
  HEAD6: ${{ github.event.push.deleted }}
  HEAD7: ${{ github.event.push.forced }}
  HEAD8: ${{ github.event.push.head_commit.id }}
  HEAD28: ${{ github.event.push.head_commit.thee_id }}
  HEAD9: ${{ github.event.push.ref }}
  HEAD0: ${{ github.event.push. }}
  HEAD11: ${{ github.event.push. }}

jobs:
  flake8-or-mypy:
    strategy:
      fail-fast: false
      matrix:
        task: [flake8, mypy]

    name: ${{ matrix.task }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Determine modified files"
        run: |
          git fetch origin $BASE $HEAD
          DIFF=$(git diff --diff-filter=d --name-only $BASE...$HEAD -- "*.py")
          echo "modified files:"
          echo "$DIFF"
          echo "diff=${DIFF//$'\n'/$' '}" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        if: env.diff != ''
        with:
          python-version: 3.8

      - name: "Install dependencies"
        if: env.diff != ''
        run: |
          python -m pip install --upgrade pip ${{ matrix.task }}
          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes

      - name: "flake8: Lint modified files"
        continue-on-error: true
        if: env.diff != '' && matrix.task == 'flake8'
        run: |
          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}

      - name: "mypy: Type check modified files"
        continue-on-error: true
        if: env.diff != '' && matrix.task == 'mypy'
        run: |
          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
